#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo """
 _____        _  _                        _____ 
/__   \  ___ | || | _   _   ___   /\ /\   \_   \\
  / /\/ / _ \| || || | | | / _ \ / / \ \   / /\/
 / /   |  __/| || || |_| || (_) |\ \_/ //\/ /_  
 \/     \___||_||_| \__, | \___/  \___/ \____/  
                    |___/                       

Remember to commit and push updated build if you are going to merge changes to master :)
"""
